version: '2'

services:
  github-releases-notifier:
    restart: always
    image: njohnstone2/github-releases-notifier:latest
    environment:
      - GITHUB_TOKEN=ghp_xxxx
      - INTERVAL=1m
      - LOG_LEVEL=info
      - SLACK_TOKEN=xoxb-xxxx
      - SLACK_CHANNEL=general
    command:
      - '-t=golang/go'
      - '-r=justwatchcom/elasticsearch_exporter'
      - '-r=justwatchcom/gopass'
      - '-r=justwatchcom/sql_exporter'
      - '-r=kubernetes/minikube'
      - '-r=prometheus/prometheus'
