apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-releases-notifier
  labels:
    {{- include "github-releases-notifier.labels" . | nindent 4 }}
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "github-releases-notifier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "github-releases-notifier.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: github-releases-notifier
          env:
            - name: INTERVAL
              value: {{ .Values.interval }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-releases-notifier
                  key: GITHUB_TOKEN
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-releases-notifier
                  key: SLACK_TOKEN
            - name: SLACK_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: github-releases-notifier
                  key: SLACK_CHANNEL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    type: RollingUpdate
