{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{default .Release.Namespace .Values.namespace.name }}
  labels:
    {{- include "github-releases-notifier.labels" . | nindent 4 }}
{{- end }}
