{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: github-releases-notifier
  labels:
    {{- include "github-releases-notifier.labels" . | nindent 4 }}
  namespace: {{default .Release.Namespace .Values.namespace.name }}
type: Opaque
data:
  {{- with .Values.secret }}
  GITHUB_TOKEN: {{ .github_token | b64enc }}
  SLACK_TOKEN: {{ .slack_token | b64enc}}
  SLACK_CHANNEL: {{ .slack_channel | b64enc }}
  {{- end }}
{{- end }}
