name: Publish Artifacts

on:
  push:
    branches: [ "github_ci" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPO: ${{ github.repository }}

jobs:
  publish-artifacts:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Create release artifacts
      run: make release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: upload helm chart
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/github-releases-notifier-helm-3-chart-0.1.3.tgz
        asset_name: github-releases-notifier-helm-3-chart-0.1.3.tgz
        asset_content_type: application/gzip
    
    # - name: Upload Artifacts
    #   uses: actions/upload-artifact@v3
    #   with: 
    #     name: artifacts
    #     path: release
