name: Publish Artifacts

on:
  push:
    branches: [ "github_ci" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPO: ${{ github.repository }}

jobs:
  publish-artifacts:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Create release artifacts
      run: make release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: artifacts
        path: release
